import './globals.css'
import Link from "next/link";

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by zzeri',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li>
        </ol>
        {children}
        <ul>
          <li><a href="/create">Create</a></li>
          <li><a href="/update/1">Update</a></li>
          <li><input type="button" value="delete"/></li>
        </ul>
      </body>
    </html>
  )
}
